# Generated by Django 4.0.5 on 2022-06-28 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='카테고리')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250, verbose_name='코멘트')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='작성자')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='제품이름')),
                ('content', models.TextField(verbose_name='제품설명')),
                ('price', models.IntegerField(verbose_name='제품가격')),
                ('size', models.CharField(max_length=200, verbose_name='제품size')),
                ('pro_img', models.ImageField(blank=True, upload_to='images/', verbose_name='제품이미지')),
                ('category', models.ManyToManyField(to='product.category', verbose_name='카테고리')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='리뷰 제목')),
                ('content', models.TextField(verbose_name='리뷰 내용')),
                ('rate', models.IntegerField(verbose_name='제품 평점')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.comment', verbose_name='댓글')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='제품이름')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='작성자')),
            ],
        ),
    ]
